### ISSUE TITLE
Image Drawing.

### ISSUE THREAD

**Issue by zxczrx123** [ltriess/kitti_scan_unfolding#1]
Thanks for your work! Can you share how the image below was drawn?This will be very useful for me！
![image](https://user-images.githubusercontent.com/37107333/107005510-c6206a80-67ca-11eb-8beb-33ab84dba30c.png)

**Comment by ltriess** [comment]
The image was produces in Blender. We created a cylinder object and put the image of the semantic label map as a texture on top. The car is a separate Blender file, you can find several models on the internet.

**Comment by zxczrx123** [comment]
Thanks for your sharing！
