### ISSUE TITLE
Any plans for code release?

### ISSUE THREAD

**Issue by yaodongC** [ltriess/kitti_scan_unfolding#2]
Hi Triess, I have read your paper and was very impressed. I am currently working on a paper for panoptic segmentation on semanticKITTI and would like to try your scan-based projection approach.
Just wondering is there any plan on releasing the code? 
Thanks.

**Comment by ltriess** [comment]
Hi yaodongC, currently it is not possible to host the code on this repo. However, there exists an old [fork](https://github.com/risteon/kitti_scan_unfolding) of this repo which still contains the first code release.

**Comment by yaodongC** [comment]
Thank you for the help!
