### ISSUE TITLE
 unfolding.projection give "Cannot find valid image indices for this point cloud and image size. "

### ISSUE THREAD

**Issue by yaodongC** [ltriess/kitti_scan_unfolding#3]
I am using your code on the semanticKITTI dataset, and function: unfolding.projection() raise the following error:

**"Cannot find valid image indices for this point cloud and image size. "
IndexError: Cannot find valid image indices for this point cloud and image size. Are you sure you entered the correct image size? This function only works with raw KITTI HDL-64 point clouds (no ego motion-corrected data allowed)!**

This unfolding.projection() works as expected on the provided "sample_raw.bin".
And I am using ".bin" files from the semanticKITTI dataset.

Are there any changes that I need to make to use your code on the semanticKITTI dataset?
Thanks in advance.

**Comment by yaodongC** [comment]
rows = unfolding.get_kitti_rows(points)
The projected rows range from **297 to 805**
whereas the column range is as expected

**Comment by ltriess** [comment]
Please refer to the [readme](https://github.com/risteon/kitti_scan_unfolding/tree/master/data).

As stated there, the unfolding method only works for the raw data and not for the ego-motion corrected data. If you simply download the data indicated by SemanticKITTI, you end up downloading the ego-motion corrected data from the KITTI odometry benchmark. However, you need to use the point clouds from the raw data which are not ego-motion corrected (you find them [here](http://www.cvlibs.net/datasets/kitti/raw_data.php)). The labels provided by SemanticKITTI also match this data.

The development kit of the odometry benchmark shows the mapping for the sequences from odometry to raw:
Nr. | Sequence name | Start | End
--- | --- | --- | ---
00 | 2011_10_03_drive_0027 | 000000 | 004540
01 | 2011_10_03_drive_0042 | 000000 | 001100
02 | 2011_10_03_drive_0034 | 000000 | 004660
03 | 2011_09_26_drive_0067 | 000000 | 000800
04 | 2011_09_30_drive_0016 | 000000 | 000270
05 | 2011_09_30_drive_0018 | 000000 | 002760
06 | 2011_09_30_drive_0020 | 000000 | 001100
07 | 2011_09_30_drive_0027 | 000000 | 001100
08 | 2011_09_30_drive_0028 | 001100 | 005170
09 | 2011_09_30_drive_0033 | 000000 | 001590
10 | 2011_09_30_drive_0034 | 000000 | 001200

**Comment by yaodongC** [comment]
Thank you for the help! 
I forgot to check the readme in the data folder.

**Comment by chubukeji** [comment]
@ltriess hello，the 03: 2011_09_26_drive_0067 can't be found in official website. Do you have this dataset? Or，do you know why it can't be found? my Email 2661076951@qq.com

**Comment by ltriess** [comment]
Hi, no I don't have this sequence. It is missing from the raw data.
